"""LENS /target — name the weekly return, and see what it actually demands.

/geometry answers "what does this configuration earn?". This page inverts it,
because that is the direction the question is actually asked in: the target is
fixed (10%/week compounds €325 to €37.5M in 2.35 years — the arithmetic is
right), and what's unknown is the edge it costs.

Every cell states its requirement as an **edge over the measured random-entry
baseline**, not over zero. That distinction is the entire value of the page. A
55% win rate sounds impossible and a 21% win rate sounds easy, but at R:R 4
random already gives you 20.7% and at R:R 1 it gives 49.9% — so the second is
the harder ask by a wide margin. Priced against the right floor, cells that look
alike separate into research problems and fantasies.

Baselines come from results/barrier_baseline.json — 63k forward-walks per
direction over 7 years of hourly bars, regenerated by research/barrier_test.py.
Nothing here is a model's guess about what a coin gets.

What the page cannot do is tell you whether you can supply the edge. It prices
the ask; supplying it is the open problem, and the ledger's answer so far is on
the page too.
"""

from __future__ import annotations

import json

from . import geometry as G
from .paths import RESULTS
from .theme import shell

WEEKLY_TARGET = 0.10          # his bar: 8–12%/week, 10 the round number
RISK_LEVELS = [1.5, 2.0, 3.0, 5.0]
TRADES_WEEK = [2, 3, 5, 10]
RRS = [1.0, 2.0, 3.0, 4.0, 6.0, 8.0]

# Prop account: breaching the drawdown ends it, so the cap is a hard wall rather
# than a preference. 1.5% risk against a 3% cap survives exactly two losses.
PROP_MAX_DD = 0.03
PROP_RISK = 1.5

# How hard an edge is to believe. Calibrated against the one number we have:
# the book runs ~4pp BELOW random today, and beating random by 10pp at high R:R
# is already an exceptional selection filter.
def _tone(pp: float) -> tuple[str, str]:
    if pp <= 6:
        return "ok", "plausible"
    if pp <= 12:
        return "warn", "hard"
    if pp <= 20:
        return "bad", "very hard"
    return "no", "fantasy"


def _baseline() -> dict | None:
    try:
        with open(RESULTS / "barrier_baseline.json") as fh:
            d = json.load(fh)
        return d if d.get("rr_baseline") else None
    except Exception:
        return None


def render() -> str:
    bl = _baseline()
    if not bl:
        return shell("/target", "Target",
                     "<p class='lead'>No measured baseline yet — run "
                     "<span class='m'>python3 research/barrier_test.py</span>.</p>",
                     meta="what the target costs")

    sigma = bl["sigma"]
    rr_base = {float(k): v["win_rate"] for k, v in bl["rr_baseline"].items()}

    def cells(risk):
        out = []
        for rr in RRS:
            if rr not in rr_base:
                continue
            for n in TRADES_WEEK:
                c = G.target_cell(WEEKLY_TARGET, rr, risk, n, sigma, rr_base[rr])
                if c:
                    out.append(c)
        return sorted(out, key=lambda c: c["edge_pp"])

    # ── the ask, stated plainly ──────────────────────────────────────────────
    wk = WEEKLY_TARGET
    head = (
        f'<p class="lead top">{wk:.0%} a week compounds <b>€325 → €37.5M in '
        f'2.35 years</b>, and <b>€487 by 1 September</b>. The arithmetic is right; '
        f'this page is about what it costs. Every requirement below is stated as '
        f'an <b>edge over a measured random entry</b> — {bl["bars"]:,} hourly bars, '
        f'{bl["from"]} to {bl["to"]}, walked forward to whichever barrier hits '
        f'first. Beating zero is not the job. Beating that floor is.</p>'
    )

    # ── the floor itself ─────────────────────────────────────────────────────
    frows = "".join(
        f"<tr><td class='m'>{rr:.0f}</td>"
        f"<td class='m'>{bl['rr_baseline'][str(rr)]['stop_pct']:.2f}%</td>"
        f"<td class='m'>{bl['rr_baseline'][str(rr)]['target_pct']:.2f}%</td>"
        f"<td class='m'>{rr_base[rr]:.1%}</td>"
        f"<td class='m'>{1/(1+rr):.1%}</td></tr>"
        for rr in RRS if rr in rr_base)
    floor = (
        "<h2>The floor you are beating</h2>"
        "<p class='lead'>A random entry is not worth zero — at R:R 4 it wins "
        "20.7% of the time, because a near stop is touched more often than a far "
        "target. <b>The higher the R:R, the lower the bar in absolute terms</b>, "
        "which is why a 21% win rate at R:R 8 and a 50% win rate at R:R 1 are not "
        "remotely the same achievement.</p>"
        "<table><tr><th>R:R</th><th>stop</th><th>target</th>"
        "<th>random WR (measured)</th><th>theory 1/(1+R)</th></tr>"
        + frows + "</table>"
    )

    # ── feasibility maps ─────────────────────────────────────────────────────
    maps = []
    for risk in RISK_LEVELS:
        cs = cells(risk)
        if not cs:
            continue
        best = cs[0]
        rows = []
        for c in cs[:9]:
            tone, word = _tone(c["edge_pp"])
            rows.append(
                f"<tr class='{tone}'><td class='m'>{c['rr']:.0f}</td>"
                f"<td class='m'>{c['trades_per_week']:g}</td>"
                f"<td class='m'>{c['stop_pct']:.2f}%</td>"
                f"<td class='m'>{c['target_pct']:.2f}%</td>"
                f"<td class='m'>{c['need_wr']:.1%}</td>"
                f"<td class='m'>{c['random_wr']:.1%}</td>"
                f"<td class='m edge'>{c['edge_pp']:+.1f}pp</td>"
                f"<td class='m'>{word}</td>"
                f"<td class='m'>{c['dd_10']:.0%}</td>"
                f"<td class='m'>{c['leverage']:.1f}×</td></tr>")
        maps.append(
            f"<h3>Risking {risk:g}% of the account per trade</h3>"
            f"<p class='note' style='margin:0 0 8px'>Cheapest cell: "
            f"<b>R:R {best['rr']:.0f} at {best['trades_per_week']:g} trades/week</b> "
            f"— needs a {best['need_wr']:.1%} win rate, which is "
            f"<b>{best['edge_pp']:+.1f}pp</b> over random. Ten losses in a row "
            f"costs {best['dd_10']:.0%} of the account.</p>"
            "<table><tr><th>R:R</th><th>tr/wk</th><th>stop</th><th>target</th>"
            "<th>need WR</th><th>random</th><th>edge</th><th></th>"
            "<th>10-loss DD</th><th>lev</th></tr>" + "".join(rows) + "</table>")

    body_maps = ("<h2>What 10%/week costs</h2>"
                 "<p class='lead'>Sorted by the edge required, cheapest first. The "
                 "pattern is consistent and it is the actionable finding: <b>higher "
                 "R:R and more trades per week both lower the edge you must supply.</b> "
                 "Frequency does it by shrinking the per-trade return needed; R:R does "
                 "it by lowering the floor faster than it lowers the requirement.</p>"
                 + "".join(maps))

    # ── the prop wall ────────────────────────────────────────────────────────
    max_r2 = G.max_risk_for_drawdown_cap(PROP_MAX_DD, 2)
    max_r5 = G.max_risk_for_drawdown_cap(PROP_MAX_DD, 5)
    max_r10 = G.max_risk_for_drawdown_cap(PROP_MAX_DD, 10)
    prop_cell = G.target_cell(WEEKLY_TARGET, 8.0, max_r10, 10, sigma,
                              rr_base.get(8.0, 0.12))
    p2 = (1 - 0.21) ** 2
    prop = (
        "<h2>The prop account is a different problem</h2>"
        f"<p class='lead'>A {PROP_MAX_DD:.0%} hard drawdown cap at "
        f"{PROP_RISK:g}% risk per trade buys you <b>exactly two losing trades</b>. "
        f"At the ~21% win rate that a 10%/week R:R-8 cell needs, two losses in a row "
        f"is a <b>{p2:.0%}</b> event — not a tail, the default outcome. The cap does "
        "not limit your drawdown so much as it sets a trade count before the account "
        "ends.</p>"
        '<div class="conf">'
        f'<div class="kv"><span class="k">survive 2 losses</span>'
        f'<span class="v">{max_r2:.2f}%</span><span class="s">max risk/trade</span></div>'
        f'<div class="kv"><span class="k">survive 5</span>'
        f'<span class="v">{max_r5:.2f}%</span><span class="s">max risk/trade</span></div>'
        f'<div class="kv"><span class="k">survive 10</span>'
        f'<span class="v">{max_r10:.2f}%</span><span class="s">max risk/trade</span></div>'
        "</div>"
        + (f"<p class='note'>At <b>{max_r10:.2f}%</b> risk — the level that survives a "
           f"ten-loss run inside the cap — reaching 10%/week at R:R 8 and 10 trades a "
           f"week needs a <b>{prop_cell['need_wr']:.1%}</b> win rate, "
           f"<b>{prop_cell['edge_pp']:+.1f}pp</b> over random. That is the honest prop "
           "number, and it is far above the hedge-account version of the same target "
           "because the drawdown cap forces the risk down by roughly 5×.</p>"
           if prop_cell else
           f"<p class='note'>At {max_r10:.2f}% risk no cell reaches 10%/week — the "
           "drawdown cap and the target are mutually exclusive at this R:R.</p>")
        + "<p class='note'>The order matters: <b>prove the edge on the hedge account, "
        "then port it.</b> A prop evaluation is a test of an edge you already have, "
        "not a place to discover one — the cap ends the experiment long before the "
        "sample is large enough to tell edge from variance.</p>"
    )

    # ── the one honest calibration point ─────────────────────────────────────
    ledger = (
        "<h2>Where the book actually sits</h2>"
        "<p class='lead'>One number calibrates every table above. The realised "
        "ledger is <b>39.4% at ~1.31R</b>. A random entry at 1.31R wins about "
        "<b>43%</b>. So the book has been running roughly <b>4pp below random</b> — "
        "the selection was not adding, and friction did the rest.</p>"
        "<p class='note'>That is not a verdict on whether the edge can exist; those "
        "trades were taken on a geometry where friction was half the stop, at a 2.1-hour "
        "median hold, using setups later disarmed for failing out of sample. It is the "
        "honest starting point: <b>the gap to 10%/week is not +9pp, it is +13pp from "
        "where the book stands.</b> Any plan that does not name where those points come "
        "from is a wish.</p>"
        "<p class='note'>The cheapest cells all say the same thing — <b>high R:R, more "
        "trades, small risk</b>. That is the search space. It is also exactly what "
        "<a href='/edge'>/edge</a> and the breeder already scan, so the machinery to "
        "hunt it exists; what has been missing is the number it has to beat.</p>"
    )

    body = head + floor + body_maps + prop + ledger + (
        '<p class="foot"><a href="/geometry">→ where the geometry comes from</a> · '
        '<a href="/edge">→ live strategy search</a><br>'
        '<span class="m">python3 research/barrier_test.py</span> regenerates the '
        'measured floor.</p>')

    css = (
        "<style>"
        "h2{font-family:var(--mono);font-size:11px;letter-spacing:.16em;"
        "text-transform:uppercase;color:var(--faint);margin:34px 0 10px;font-weight:600}"
        "h3{font-family:var(--mono);font-size:12px;color:var(--ink);margin:24px 0 4px;"
        "font-weight:600}"
        "p.lead{color:var(--dim);font-size:13.5px;line-height:1.65;max-width:76ch;margin:0 0 14px}"
        "p.lead.top{color:var(--ink);font-size:14px;margin-bottom:20px}"
        "p.note{color:var(--faint);font-size:12.5px;line-height:1.6;max-width:76ch;margin:12px 0 0}"
        "p.foot{margin-top:34px;font-size:12.5px;color:var(--faint);line-height:1.9}"
        "p.foot a{color:var(--accent);text-decoration:none;margin-right:4px}"
        ".m{font-family:var(--mono)}"
        "table{border-collapse:collapse;width:100%;font-size:13px;margin-top:4px}"
        "th{text-align:left;color:var(--faint);font-family:var(--mono);font-size:10px;"
        "text-transform:uppercase;letter-spacing:.12em;padding:7px 9px;"
        "border-bottom:1px solid var(--line);white-space:nowrap}"
        "td{padding:8px 9px;border-bottom:1px solid var(--line)}"
        "td.m{font-family:var(--mono);font-size:12.5px;white-space:nowrap}"
        "td.edge{font-weight:700}"
        "tr.ok td.edge{color:var(--long)} tr.warn td.edge{color:var(--amber)}"
        "tr.bad td.edge{color:var(--short)} tr.no td.edge{color:var(--short);opacity:.6}"
        "tr.no td{opacity:.55}"
        ".conf{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;"
        "background:var(--line);border:1px solid var(--line);border-radius:10px;"
        "overflow:hidden;margin:6px 0}"
        ".kv{background:var(--panel);padding:12px 14px}"
        ".kv .k{display:block;font-family:var(--mono);font-size:9.5px;letter-spacing:.14em;"
        "text-transform:uppercase;color:var(--faint)}"
        ".kv .v{display:block;font-family:var(--mono);font-size:17px;font-weight:600;margin:5px 0 3px}"
        ".kv .s{display:block;font-size:11.5px;color:var(--dim);line-height:1.45}"
        "@media(max-width:720px){.conf{grid-template-columns:1fr}}"
        "</style>")
    return shell("/target", "Target", body, head_extra=css,
                 meta="what the target costs")
